---
name: consul-test
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: single_consul
  version: latest

stemcells:
- alias: default
  os: bosh-warden-boshlite-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: consul-test
  instances: 3
  persistent_disk: 1024
  stemcell: default
  networks:
  - name: consul1
    static_ips:
    - 10.244.68.3
    - 10.244.68.4
    - 10.244.68.5
  jobs:
  - name: consul
    release: single_consul
    properties:
       consul:
         join_hosts:
         - 10.244.68.3
         - 10.244.68.4
         - 10.244.68.5
         data_center: DC1
update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 50
  serial: true
  update_watch_time: 5000-120000
